// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSX3tBok1wKtKBhoXFjZ6IQCLd8mF59vc',
    appId: '1:73571356917:web:e7ddacb64beb22a04035bc',
    messagingSenderId: '73571356917',
    projectId: 'cloneudmy',
    authDomain: 'cloneudmy.firebaseapp.com',
    storageBucket: 'cloneudmy.appspot.com',
    measurementId: 'G-8H8PG55MBK',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSX3tBok1wKtKBhoXFjZ6IQCLd8mF59vc',
    appId: '1:73571356917:web:d63529d6a4c3ee4e4035bc',
    messagingSenderId: '73571356917',
    projectId: 'cloneudmy',
    authDomain: 'cloneudmy.firebaseapp.com',
    storageBucket: 'cloneudmy.appspot.com',
    measurementId: 'G-1BJP7H892E',
  );
}
